[global]
daemonize = no
error_log = /proc/self/fd/2
log_limit = 8192

[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000

pm = static
pm.max_children = 2
pm.max_requests = 500
request_terminate_timeout = 600s

clear_env = no
catch_workers_output = yes
decorate_workers_output = no

php_admin_value[memory_limit] = 64M
php_admin_value[opcache.memory_consumption] = 24
php_admin_value[opcache.interned_strings_buffer] = 4
php_admin_value[opcache.max_accelerated_files] = 8000
php_admin_value[opcache.validate_timestamps] = 0
php_admin_value[realpath_cache_size] = 256K
php_admin_value[realpath_cache_ttl] = 600
